services:
  kf2-server:
    image: ghcr.io/lechuga16/docker-kf2:latest
    container_name: kf2-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - kf2_data:/data
    environment:
      - LGSM_PASSWORD=${LGSM_PASSWORD}
      - SSH_PORT=${SSH_PORT}
      - SSH_KEY=${SSH_KEY}

      - KF2_GAME_PORT=${KF2_GAME_PORT:-7777}
      - KF2_QUERY_PORT=${KF2_QUERY_PORT:-27015}
      - KF2_WEBADMIN_PORT=${KF2_WEBADMIN_PORT:-8080}
      - KF2_STEAM_PORT=${KF2_STEAM_PORT:-20560}
      - KF2_NTP_PORT=${KF2_NTP_PORT:-123}

      - KF2_WEBADMIN=${KF2_WEBADMIN:-false}
      - KF2_ADMIN_PASSWORD=${KF2_ADMIN_PASSWORD}

      - KF2_WORKSHOP=${KF2_WORKSHOP:-[]}
      - KF2_TICKRATE=${KF2_TICKRATE:-30}
      
volumes:
  kf2_data:
    name: kf2_data
