services:
  kf2-dev:
    build:
      dockerfile: Dockerfile
      context: .
    image: kf2-dev-local
    container_name: kf2-dev
    volumes:
      - dev_data:/data
    environment:
      - LGSM_PASSWORD=${LGSM_PASSWORD}
      - SSH_KEY=${SSH_KEY}
      - KF2_WEBADMIN=${KF2_WEBADMIN:-false}
    ports:
      - "${KF2_GAME_PORT}:7777/udp"
      - "${KF2_QUERY_PORT}:27015/udp"
      - "${KF2_WEBADMIN_PORT}:8080/tcp"
      - "${KF2_STEAM_PORT}:20560/udp"
      - "${KF2_NTP_PORT}:123/udp"
      - "${SSH_PORT}:22/tcp"

volumes:
  dev_data:
    name: dev_data